name: Publish PyPI Package

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - '.github/*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Twine
        run: >-
          pip install twine

      - name: Build a binary wheel and a source tarball
        run: >-
          python setup.py sdist bdist_wheel
          twine check dist/*

      - name: Publish to PyPI
          if: startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
          